from __future__ import annotations

import uuid

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.document import Document, DocumentStatus


def get_by_workspace_and_checksum(
    db: Session, *, workspace_id: uuid.UUID, checksum_sha256: str
) -> Document | None:
    return db.execute(
        select(Document).where(
            Document.workspace_id == workspace_id,
            Document.checksum_sha256 == checksum_sha256,
        )
    ).scalar_one_or_none()


def create(
    db: Session,
    *,
    id: uuid.UUID,
    workspace_id: uuid.UUID,
    uploaded_by: uuid.UUID | None,
    filename: str,
    mime_type: str,
    size_bytes: int,
    checksum_sha256: str,
    storage_key: str,
) -> Document:
    # `id` is generated by the caller, not left to the model's own default,
    # because the storage key (built before this insert runs -- storage
    # must succeed first) already embeds this same document ID. The row's
    # id and the file's location must agree.
    document = Document(
        id=id,
        workspace_id=workspace_id,
        uploaded_by=uploaded_by,
        filename=filename,
        mime_type=mime_type,
        size_bytes=size_bytes,
        checksum_sha256=checksum_sha256,
        storage_key=storage_key,
        status=DocumentStatus.UPLOADED,
    )
    db.add(document)
    db.flush()
    db.refresh(document)
    return document
