from __future__ import annotations

import uuid
from datetime import UTC, datetime

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.document import Document, DocumentStatus


def get_by_workspace_and_checksum(
    db: Session, *, workspace_id: uuid.UUID, checksum_sha256: str
) -> Document | None:
    return db.execute(
        select(Document).where(
            Document.workspace_id == workspace_id,
            Document.checksum_sha256 == checksum_sha256,
        )
    ).scalar_one_or_none()


def get_by_id_for_workspace(
    db: Session, *, workspace_id: uuid.UUID, document_id: uuid.UUID
) -> Document | None:
    """Scoped to `workspace_id` in the query itself (not checked
    afterward) so a document ID from one workspace can never be looked up
    through another — the same IDOR-defense shape as every other
    workspace-scoped lookup in this codebase."""
    return db.execute(
        select(Document).where(
            Document.id == document_id,
            Document.workspace_id == workspace_id,
        )
    ).scalar_one_or_none()


def create(
    db: Session,
    *,
    id: uuid.UUID,
    workspace_id: uuid.UUID,
    uploaded_by: uuid.UUID | None,
    filename: str,
    mime_type: str,
    size_bytes: int,
    checksum_sha256: str,
    storage_key: str,
) -> Document:
    # `id` is generated by the caller, not left to the model's own default,
    # because the storage key (built before this insert runs -- storage
    # must succeed first) already embeds this same document ID. The row's
    # id and the file's location must agree.
    document = Document(
        id=id,
        workspace_id=workspace_id,
        uploaded_by=uploaded_by,
        filename=filename,
        mime_type=mime_type,
        size_bytes=size_bytes,
        checksum_sha256=checksum_sha256,
        storage_key=storage_key,
        status=DocumentStatus.UPLOADED,
    )
    db.add(document)
    db.flush()
    db.refresh(document)
    return document


def mark_processing(db: Session, *, document: Document) -> Document:
    """Committed by the caller as its own transaction, separate from the
    extraction attempt that follows -- see
    app/services/document_service.py's process_document() docstring for
    why that separation matters (a crash mid-extraction must leave the
    document honestly at PROCESSING, never falsely at PARSED)."""
    document.status = DocumentStatus.PROCESSING
    document.processing_started_at = datetime.now(UTC)
    db.add(document)
    db.flush()
    db.refresh(document)
    return document


def mark_parsed(db: Session, *, document: Document, page_count: int | None) -> Document:
    document.status = DocumentStatus.PARSED
    document.page_count = page_count
    document.failure_reason = None
    document.processing_completed_at = datetime.now(UTC)
    db.add(document)
    db.flush()
    db.refresh(document)
    return document


def mark_failed(db: Session, *, document: Document, reason: str) -> Document:
    document.status = DocumentStatus.FAILED
    document.failure_reason = reason
    document.processing_completed_at = datetime.now(UTC)
    db.add(document)
    db.flush()
    db.refresh(document)
    return document


def mark_cleaned(db: Session, *, document: Document) -> Document:
    """No new content is stored for `CLEANED` itself -- cleaned text
    isn't persisted anywhere (see `app/ingestion/cleaning.py`'s module
    docstring on why re-running cleaning on retry is the deliberate
    design, not a gap) -- this only records that the document reached
    this durable checkpoint, so a crash before chunking completes leaves
    it honestly at `CLEANED`, not falsely `CHUNKED`."""
    document.status = DocumentStatus.CLEANED
    document.failure_reason = None
    db.add(document)
    db.flush()
    db.refresh(document)
    return document


def mark_chunked(db: Session, *, document: Document) -> Document:
    """Callers must insert this document's `document_chunks` rows (see
    `document_chunk_repository.bulk_create()`) in the *same* transaction
    as this call, then commit both together -- never call this alone.
    See `document_service.process_document()` for the exact ordering."""
    document.status = DocumentStatus.CHUNKED
    document.failure_reason = None
    document.processing_completed_at = datetime.now(UTC)
    db.add(document)
    db.flush()
    db.refresh(document)
    return document


def mark_embedded(db: Session, *, document: Document) -> Document:
    """Callers must update every one of this document's `document_chunks`
    rows (see `document_chunk_repository.set_embeddings()`) in the *same*
    transaction as this call, then commit both together -- the same
    atomicity contract as `mark_chunked()`, so a document is never
    observably `EMBEDDED` with some chunks still missing a vector."""
    document.status = DocumentStatus.EMBEDDED
    document.failure_reason = None
    document.processing_completed_at = datetime.now(UTC)
    db.add(document)
    db.flush()
    db.refresh(document)
    return document


def mark_indexed(db: Session, *, document: Document) -> Document:
    """No separate build step precedes this -- pgvector's HNSW index
    (migration `0005`) is maintained transactionally as part of the same
    `UPDATE` that `mark_embedded()`'s caller already committed, so a
    document's chunks are already covered by the index the instant
    `EMBEDDED` is durably committed. This transition exists to preserve
    the documented lifecycle (docs/RAG_DESIGN.md) and give downstream
    consumers (retrieval, observability) an explicit, auditable signal
    that indexing is guaranteed complete, not to perform additional
    work."""
    document.status = DocumentStatus.INDEXED
    document.failure_reason = None
    db.add(document)
    db.flush()
    db.refresh(document)
    return document


def mark_ready(db: Session, *, document: Document) -> Document:
    """The terminal success state for the ingestion pipeline (Issue #3).
    No additional work happens at this transition today -- it marks a
    document as available for retrieval once Issue #4 exists."""
    document.status = DocumentStatus.READY
    document.failure_reason = None
    document.processing_completed_at = datetime.now(UTC)
    db.add(document)
    db.flush()
    db.refresh(document)
    return document
